# Generated by Django 6.0 on 2025-12-18 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=255)),
                ('tipo_solo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mercado', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('compra_semanal_kg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('residuo_semanal_kg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('residuo_mensal_kg', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAdubacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('peso_residuos_kg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ph_pre_aplicacao', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ph_pos_aplicacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ndvi_pos_aplicacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('resultado_analise', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.areaaplicacao')),
            ],
        ),
    ]
